import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/ui/Header";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import TenstackQuery from "../components/TenstackQuery";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TenstackQuery>
        <ClerkProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Header />
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
              {children}
              <footer className="w-full py-4 text-center">
                <p className="text-sm font-medium text-gray-600 dark:text-gray-400 flex items-center justify-center gap-1 hover:scale-105 transition-transform duration-300">
                  Made with
                  <span className="animate-pulse text-red-500 mx-1">❤️</span>
                  by
                  <span className="bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent font-semibold hover:from-pink-600 hover:to-purple-600 transition-all duration-300">
                    Navtesh
                  </span>
                </p>
              </footer>
              <Toaster />
            </ThemeProvider>
          </body>
        </ClerkProvider>
      </TenstackQuery>
    </html>
  );
}
